# Generated by Django 4.0.4 on 2022-05-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='category_subscription',
            field=models.ManyToManyField(to='main.category'),
        ),
    ]
