# Generated by Django 4.0.4 on 2022-05-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(null=True, upload_to='images/<django.db.models.fields.CharField>/', verbose_name='Изображения'),
        ),
    ]
