# Generated by Django 4.0.4 on 2022-05-18 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_category_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='category_subscription',
            new_name='category_subscriptions',
        ),
    ]
